name: Update playlist from Pastebin

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download playlist from Pastebin
      run: |
        curl -s https://pastebin.com/raw/8GpCCkhf -o playlist.m3u
    - name: Commit and push
      run: |
        git config --global user.name "GitHub Bot"
        git config --global user.email "bot@example.com"
        git add playlist.m3u
        git commit -m "Auto-update playlist" || echo "No changes"
        git push
